# Generated by Django 4.2.4 on 2023-11-16 05:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('asunto', models.CharField(blank=True, choices=[('Asunto', 'Asunto (Click para seleccionar)'), ('No especificado', 'No especificado'), ('Dolor de cabeza', 'Dolor de cabeza'), ('Dolor de vientre', 'Dolor de vientre'), ('fiebre', 'fiebre'), ('otro', 'otro')], default='Asunto', max_length=45, null=True, verbose_name='Asunto')),
                ('phone_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('schedule', models.CharField(blank=True, max_length=40, null=True, verbose_name='Fecha')),
                ('leido', models.BooleanField(default=False, verbose_name='Leido')),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id Doctor')),
                ('foto', models.ImageField(upload_to='doctores')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Contenido de Mensaje')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('previa', models.CharField(max_length=200, verbose_name='Previa de Post')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Portada')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de post')),
                ('contenido', ckeditor.fields.RichTextField(max_length=7000, verbose_name='Contenido')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentistsapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('presentacion', models.TextField(max_length=500)),
                ('plazas', models.BooleanField(default=True)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('acerca', ckeditor.fields.RichTextField(max_length=15000, verbose_name='Contenido')),
                ('duracion', models.CharField(max_length=255, verbose_name='Duracion de Curso')),
                ('tutor', models.CharField(max_length=200, verbose_name='Profesor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriacurso', to='dentistsapp.categoriacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=1000)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dentistsapp.post')),
            ],
        ),
    ]
