# Generated by Django 4.2.4 on 2023-11-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='leido',
        ),
    ]
