# Generated by Django 4.2.4 on 2023-11-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0002_remove_cita_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
    ]
