# Generated by Django 4.2.4 on 2023-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0003_cita_leido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='plazas',
        ),
        migrations.AddField(
            model_name='curso',
            name='descuentos',
            field=models.BooleanField(default=True, verbose_name='descuentos disponibles'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
