# Generated by Django 4.2.4 on 2023-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0004_remove_curso_plazas_curso_descuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=2, upload_to='cursos', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
