# Generated by Django 4.2.4 on 2023-11-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0005_curso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='presentacion',
        ),
    ]
