# Generated by Django 4.2.4 on 2023-11-20 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dentistsapp', '0007_alter_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descuentos',
            field=models.BooleanField(default=True, verbose_name='Curso Disponible'),
        ),
    ]
