# Generated by Django 4.2.4 on 2023-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0008_alter_comentario_name_alter_curso_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='enlace',
            field=models.CharField(default='N/A', max_length=1000, verbose_name='Enlace de pago'),
        ),
    ]
