# Generated by Django 4.2.4 on 2023-11-23 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0009_curso_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='lecciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='N/A', max_length=5000), default='N/A', size=None),
        ),
    ]
