# Generated by Django 4.2.4 on 2023-11-23 19:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0015_alter_curso_lecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='lecciones',
            field=ckeditor.fields.RichTextField(max_length=15000, verbose_name='Lecciones'),
        ),
    ]
