# Generated by Django 4.2.4 on 2023-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0016_alter_curso_lecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='enlace',
            field=models.CharField(default='No Asignado', max_length=1000, verbose_name='Enlace de pago'),
        ),
    ]
