# Generated by Django 4.2.4 on 2023-11-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0017_alter_curso_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='enlace',
            field=models.CharField(default=list, max_length=1000, verbose_name='Enlace de pago'),
        ),
    ]
