# Generated by Django 4.2.4 on 2023-11-23 20:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0023_alter_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='lecciones',
            field=ckeditor.fields.RichTextField(default='N/A', max_length=15000, verbose_name='Lecciones'),
        ),
    ]
