# Generated by Django 4.2.4 on 2023-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0024_alter_curso_lecciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('unidad', models.CharField(max_length=200, verbose_name='Unidad')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
