# Generated by Django 4.2.4 on 2023-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0025_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correos', models.EmailField(max_length=254, verbose_name='Correos')),
            ],
        ),
    ]
