# Generated by Django 4.2.4 on 2023-11-26 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistsapp', '0026_correos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='publico',
            field=ckeditor.fields.RichTextField(default='N/A', max_length=15000, verbose_name='Público objetivo'),
        ),
    ]
